version: '3.1'
services:
  postgres_phygital_dwh:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'phygital_dwh'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
        - '5557:5432'
