version: '3.1'
services:
  postgres_phygital_dwh:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'phygital_server'
      POSTGRES_PASSWORD: 'admin'
    ports:
        - '5448:5432'
    volumes:
        - './pgdata:/var/lib/postgresql/data'
